ARG REPO=library
FROM ${REPO}/haproxy:lts-alpine

EXPOSE 2375
ENV POST_ALL=0 \
    DELETE_ALL=0 \
    GET_AUTH=0 \
    GET_BUILD=0 \
    GET_COMMIT=0 \
    GET_CONFIGS=0 \
    GET_CONTAINERS=0 \
    GET_DISTRIBUTION=0 \
    GET_EVENTS=1 \
    GET_EXEC=0 \
    GET_IMAGES=0 \
    GET_INFO=0 \
    GET_NETWORKS=0 \
    GET_NODES=0 \
    GET_PING=1 \
    GET_PLUGINS=0 \
    GET_SECRETS=0 \
    GET_SERVICES=0 \
    GET_SESSION=0 \
    GET_SWARM=0 \
    GET_SYSTEM=0 \
    GET_TASKS=0 \
    GET_VERSION=1 \
    GET_VOLUMES=0 \
    POST_CONTAINERS_CREATE=0 \
    POST_CONTAINERS_PRUNE=0 \
    POST_CONTAINERS_RESIZE=0 \
    POST_CONTAINERS_START=0 \
    POST_CONTAINERS_STOP=0 \
    POST_CONTAINERS_RESTART=0 \
    POST_CONTAINERS_KILL=0 \
    POST_CONTAINERS_UPDATE=0 \
    POST_CONTAINERS_RENAME=0 \
    POST_CONTAINERS_PAUSE=0 \
    POST_CONTAINERS_UNPAUSE=0 \
    POST_CONTAINERS_ATTACH=0 \
    POST_CONTAINERS_WAIT=0 \
    POST_CONTAINERS_EXEC=0 \
    POST_VOLUMES_CREATE=0 \
    POST_VOLUMES_PRUNE=0 \
    POST_NETWORKS_CREATE=0 \
    POST_NETWORKS_PRUNE=0 \
    POST_NETWORKS_CONNECT=0 \
    POST_NETWORKS_DISCONNECT=0 \
    DELETE_NETWORKS=0 \
    DELETE_CONTAINERS=0 \
    DELETE_IMAGES=0 \
    DELETE_VOLUMES=0 \
    LOG_LEVEL=info

COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
